"""add_user_location_fields

Revision ID: 3a686a89c4c2
Revises: 5a522e143506
Create Date: 2025-10-16 14:24:59.259677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a686a89c4c2'
down_revision: Union[str, Sequence[str], None] = '5a522e143506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('saved_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('saved_longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('saved_city', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'saved_city')
    op.drop_column('users', 'saved_longitude')
    op.drop_column('users', 'saved_latitude')
    # ### end Alembic commands ###
